export const sortingOptions = [
    { value: 'number', label: 'Number (Ascending)' },
    { value: '-number', label: 'Number (Descending)' },
    { value: 'name', label: 'Name (Ascending)' },
    { value: '-name', label: 'Name (Descending)' },
    { value: 'type_1', label: 'Type 1 (Ascending)' },
    { value: '-type_1', label: 'Type 1 (Descending)' },
    { value: 'type_2', label: 'Type 2 (Ascending)' },
    { value: '-type_2', label: 'Type 2 (Descending)' },
    { value: 'total', label: 'Total (Ascending)' },
    { value: '-total', label: 'Total (Descending)' },
    { value: 'hp', label: 'HP (Ascending)' },
    { value: '-hp', label: 'HP (Descending)' },
    { value: 'attack', label: 'Attack (Ascending)' },
    { value: '-attack', label: 'Attack (Descending)' },
    { value: 'defense', label: 'Defense (Ascending)' },
    { value: '-defense', label: 'Defense (Descending)' },
    { value: 'sp_atk', label: 'Special Attack (Ascending)' },
    { value: '-sp_atk', label: 'Special Attack (Descending)' },
    { value: 'sp_def', label: 'Special Defense (Ascending)' },
    { value: '-sp_def', label: 'Special Defense (Descending)' },
    { value: 'speed', label: 'Speed (Ascending)' },
    { value: '-speed', label: 'Speed (Descending)' },
    { value: 'generation', label: 'Generation (Ascending)' },
    { value: '-generation', label: 'Generation (Descending)' },
    { value: 'legendary', label: 'Legendary (Ascending)' },
    { value: '-legendary', label: 'Legendary (Descending)' },
    { value: 'created_at', label: 'Created At (Ascending)' },
    { value: '-created_at', label: 'Created At (Descending)' },
    { value: 'updated_at', label: 'Updated At (Ascending)' },
    { value: '-updated_at', label: 'Updated At (Descending)' },
  ];
  